### ISSUE TITLE
old versions

### ISSUE THREAD

**Issue by wrt54g** [improv-wifi/sdk-ble-js#157]
Some packages are on an old version:
devdependencies:
@rollup/plugin-node-resolve 13.0.6 > 13.3.0
@rollup/plugin-typescript 8.2.1 > 8.3.2
prettier 2.3.0 > 2.6.2
rollup 2.48.0 > 2.75.5
typescript 4.2.4 > 4.7.3
dependencies:
lit 2.0.0 > 2.2.5
tslib 2.3.1 > 2.4.0
@babel/highlight 7.12.13 > 7.17.12
@babel/helper-validator-identifier 7.14.0 > 7.16.7
chalk 2.0.0 > 5.0.1
js-tokens 4.0.0 > 8.0.0
wicg-inert 3.0.0 > 3.1.1

**Comment by balloob** [comment]
that's just package.json, not package-lock.json. See #159
